markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "JensenYang Tech"
markdown: kramdown

author: "JensenYang"
atom-baseurl: "http://JensenYang.com"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
